# Generated by Django 6.1.1 on 2026-09-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('school_type', models.CharField(max_length=50)),
                ('student_phone', models.CharField(max_length=20)),
                ('parent_phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
