# Generated by Django 6.1.1 on 2026-09-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_classroom_remove_student_password_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_phone',
        ),
    ]
