# Generated by Django 6.1.1 on 2026-09-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_student_grade_remove_student_parent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='غير محدد', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='school_type',
            field=models.CharField(default='غير محدد', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='طالب', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
