# Generated by Django 6.1.1 on 2026-09-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscriptionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=100)),
                ('school_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='lessons/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو'), ('exam', 'امتحان')], max_length=20)),
                ('file', models.FileField(upload_to='study_materials/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
