# Generated by Django 6.1.1 on 2026-09-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_lesson_studymaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.CharField(choices=[('الصف الأول الابتدائي', 'الصف الأول الابتدائي'), ('الصف الثاني الابتدائي', 'الصف الثاني الابتدائي'), ('الصف الثالث الابتدائي', 'الصف الثالث الابتدائي'), ('الصف الرابع الابتدائي', 'الصف الرابع الابتدائي'), ('الصف الخامس الابتدائي', 'الصف الخامس الابتدائي'), ('الصف السادس الابتدائي', 'الصف السادس الابتدائي'), ('الصف الأول الإعدادي', 'الصف الأول الإعدادي'), ('الصف الثاني الإعدادي', 'الصف الثاني الإعدادي'), ('الصف الثالث الإعدادي', 'الصف الثالث الإعدادي')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='school_type',
            field=models.CharField(choices=[('عربي', 'عربي'), ('لغات', 'لغات')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[('عربي', 'عربي'), ('رياضيات', 'رياضيات'), ('علوم', 'علوم'), ('دراسات', 'دراسات'), ('إنجليزي', 'إنجليزي'), ('Math', 'Math'), ('English', 'English'), ('Science', 'Science'), ('English Plus', 'English Plus')], max_length=100),
        ),
        migrations.CreateModel(
            name='LessonWatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('watch_seconds', models.PositiveIntegerField(default=0)),
                ('last_position', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_stats', to='main.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_watch_stats', to='main.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='unique_student_lesson_watch_stat')],
            },
        ),
    ]
