# Generated by Django 6.1.1 on 2026-09-11 19:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_lesson_grade_alter_lesson_school_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('monthly', 'شهري'), ('full_term', 'الترم كامل')], default='monthly', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('watched_lessons', models.PositiveIntegerField(default=0)),
                ('max_lessons', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='lessonwatchstat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='selected_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='subscription_type',
            field=models.CharField(choices=[('subjects', 'مواد معينة'), ('full_term', 'الترم كامل')], default='subjects', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lessons_videos/'),
        ),
        migrations.AlterField(
            model_name='lessonwatchstat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_stats', to='main.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['grade', 'school_type', 'is_active'], name='main_lesson_grade_aea46f_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['subject', '-created_at'], name='main_lesson_subject_fb1450_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonwatchstat',
            index=models.Index(fields=['student', 'lesson'], name='main_lesson_student_af6d17_idx'),
        ),
        migrations.AddField(
            model_name='subjectsubscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_subscriptions', to='main.student'),
        ),
        migrations.AddIndex(
            model_name='subjectsubscription',
            index=models.Index(fields=['student', 'subject', 'is_active'], name='main_subjec_student_29ac45_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectsubscription',
            index=models.Index(fields=['end_date'], name='main_subjec_end_dat_97ebd0_idx'),
        ),
    ]
