# Generated by Django 6.1.1 on 2026-09-11 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_subjectsubscription_lessonwatchstat_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الامتحان')),
                ('description', models.TextField(blank=True, verbose_name='وصف الامتحان')),
                ('grade', models.CharField(choices=[('الصف الأول الابتدائي', 'الصف الأول الابتدائي'), ('الصف الثاني الابتدائي', 'الصف الثاني الابتدائي'), ('الصف الثالث الابتدائي', 'الصف الثالث الابتدائي'), ('الصف الرابع الابتدائي', 'الصف الرابع الابتدائي'), ('الصف الخامس الابتدائي', 'الصف الخامس الابتدائي'), ('الصف السادس الابتدائي', 'الصف السادس الابتدائي'), ('الصف الأول الإعدادي', 'الصف الأول الإعدادي'), ('الصف الثاني الإعدادي', 'الصف الثاني الإعدادي'), ('الصف الثالث الإعدادي', 'الصف الثالث الإعدادي')], max_length=100, verbose_name='الصف')),
                ('school_type', models.CharField(choices=[('عربي', 'عربي'), ('لغات', 'لغات')], max_length=50, verbose_name='نوع التعليم')),
                ('subject', models.CharField(choices=[('عربي', 'عربي'), ('رياضيات', 'رياضيات'), ('علوم', 'علوم'), ('دراسات', 'دراسات'), ('إنجليزي', 'إنجليزي'), ('Math', 'Math'), ('English', 'English'), ('Science', 'Science'), ('English Plus', 'English Plus')], max_length=100, verbose_name='المادة')),
                ('file', models.FileField(blank=True, null=True, upload_to='exams/', verbose_name='ملف الامتحان')),
                ('total_marks', models.PositiveIntegerField(default=100, verbose_name='إجمالي الدرجات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['grade', 'school_type', 'subject', 'is_active'], name='main_exam_grade_4998c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الواجب')),
                ('homework_type', models.CharField(choices=[('electronic', 'واجب إلكتروني'), ('paper', 'واجب ورقي')], default='electronic', max_length=20, verbose_name='نوع الواجب')),
                ('description', models.TextField(blank=True, verbose_name='وصف الواجب')),
                ('grade', models.CharField(choices=[('الصف الأول الابتدائي', 'الصف الأول الابتدائي'), ('الصف الثاني الابتدائي', 'الصف الثاني الابتدائي'), ('الصف الثالث الابتدائي', 'الصف الثالث الابتدائي'), ('الصف الرابع الابتدائي', 'الصف الرابع الابتدائي'), ('الصف الخامس الابتدائي', 'الصف الخامس الابتدائي'), ('الصف السادس الابتدائي', 'الصف السادس الابتدائي'), ('الصف الأول الإعدادي', 'الصف الأول الإعدادي'), ('الصف الثاني الإعدادي', 'الصف الثاني الإعدادي'), ('الصف الثالث الإعدادي', 'الصف الثالث الإعدادي')], max_length=100, verbose_name='الصف')),
                ('school_type', models.CharField(choices=[('عربي', 'عربي'), ('لغات', 'لغات')], max_length=50, verbose_name='نوع التعليم')),
                ('subject', models.CharField(choices=[('عربي', 'عربي'), ('رياضيات', 'رياضيات'), ('علوم', 'علوم'), ('دراسات', 'دراسات'), ('إنجليزي', 'إنجليزي'), ('Math', 'Math'), ('English', 'English'), ('Science', 'Science'), ('English Plus', 'English Plus')], max_length=100, verbose_name='المادة')),
                ('file', models.FileField(blank=True, null=True, upload_to='homework/', verbose_name='ملف الواجب')),
                ('total_marks', models.PositiveIntegerField(default=0, verbose_name='إجمالي الدرجات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['grade', 'school_type', 'subject', 'is_active'], name='main_homewo_grade_d1bf56_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomeworkQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='السؤال')),
                ('choice_a', models.CharField(max_length=500, verbose_name='الاختيار الأول')),
                ('choice_b', models.CharField(max_length=500, verbose_name='الاختيار الثاني')),
                ('choice_c', models.CharField(blank=True, max_length=500, verbose_name='الاختيار الثالث')),
                ('choice_d', models.CharField(blank=True, max_length=500, verbose_name='الاختيار الرابع')),
                ('correct_answer', models.CharField(choices=[('a', 'الاختيار الأول'), ('b', 'الاختيار الثاني'), ('c', 'الاختيار الثالث'), ('d', 'الاختيار الرابع')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('mark', models.PositiveIntegerField(default=1, verbose_name='درجة السؤال')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتيب السؤال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.homework', verbose_name='الواجب')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='الدرجة')),
                ('max_score', models.FloatField(default=0, verbose_name='الدرجة النهائية')),
                ('feedback', models.TextField(blank=True, verbose_name='ملاحظات المدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.homework', verbose_name='الواجب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_results', to='main.student', verbose_name='الطالب')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='homework_submissions/', verbose_name='إجابة الطالب')),
                ('status', models.CharField(choices=[('submitted', 'تم التسليم'), ('pending', 'قيد التصحيح'), ('graded', 'تم التصحيح')], default='submitted', max_length=20, verbose_name='حالة التسليم')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.homework', verbose_name='الواجب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='main.student', verbose_name='الطالب')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=1, verbose_name='إجابة الطالب')),
                ('is_correct', models.BooleanField(default=False, verbose_name='الإجابة صحيحة')),
                ('mark_obtained', models.PositiveIntegerField(default=0, verbose_name='الدرجة المحصلة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='main.homeworkquestion', verbose_name='السؤال')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.homeworksubmission', verbose_name='التسليم')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='الدرجة')),
                ('feedback', models.TextField(blank=True, verbose_name='ملاحظات المدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.exam', verbose_name='الامتحان')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='main.student', verbose_name='الطالب')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'exam'], name='main_examre_student_606ece_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'exam'), name='unique_student_exam_result')],
            },
        ),
        migrations.AddIndex(
            model_name='homeworkquestion',
            index=models.Index(fields=['homework', 'order'], name='main_homewo_homewor_3572c6_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworkresult',
            index=models.Index(fields=['student', 'homework'], name='main_homewo_student_a33c75_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworkresult',
            constraint=models.UniqueConstraint(fields=('student', 'homework'), name='unique_student_homework_result'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['student', 'homework'], name='main_homewo_student_49b4e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworksubmission',
            constraint=models.UniqueConstraint(fields=('student', 'homework'), name='unique_student_homework_submission'),
        ),
        migrations.AddIndex(
            model_name='homeworkanswer',
            index=models.Index(fields=['submission', 'question'], name='main_homewo_submiss_446a6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworkanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_submission_question_answer'),
        ),
    ]
