# Generated by Django 6.1.1 on 2026-09-12 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_exam_homework_homeworkquestion_homeworkresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='محادثة جديدة', max_length=200, verbose_name='عنوان المحادثة')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('student', 'الطالب'), ('ai', 'المساعد'), ('admin', 'الإدارة')], max_length=20, verbose_name='المرسل')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailableSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_type', models.CharField(choices=[('عربي', 'عربي'), ('لغات', 'لغات')], max_length=50, verbose_name='نوع التعليم')),
                ('subject_name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('is_active', models.BooleanField(default=True, verbose_name='المادة متاحة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='GradeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('الصف الأول الابتدائي', 'الصف الأول الابتدائي'), ('الصف الثاني الابتدائي', 'الصف الثاني الابتدائي'), ('الصف الثالث الابتدائي', 'الصف الثالث الابتدائي'), ('الصف الرابع الابتدائي', 'الصف الرابع الابتدائي'), ('الصف الخامس الابتدائي', 'الصف الخامس الابتدائي'), ('الصف السادس الابتدائي', 'الصف السادس الابتدائي'), ('الصف الأول الإعدادي', 'الصف الأول الإعدادي'), ('الصف الثاني الإعدادي', 'الصف الثاني الإعدادي'), ('الصف الثالث الإعدادي', 'الصف الثالث الإعدادي')], max_length=100, unique=True, verbose_name='الصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='الصف متاح')),
                ('monthly_subject_price', models.PositiveIntegerField(default=0, verbose_name='سعر المادة شهريًا')),
                ('full_term_price', models.PositiveIntegerField(default=0, verbose_name='سعر الترم الكامل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='إعدادات المنصة', max_length=100, unique=True)),
                ('curriculum_available_in_vacation', models.BooleanField(default=False, verbose_name='المنهج متاح في الإجازة')),
                ('skills_available_in_vacation', models.BooleanField(default=True, verbose_name='المهارات متاحة في الإجازة')),
                ('vacation_start_month', models.PositiveIntegerField(default=6, verbose_name='شهر بداية الإجازة')),
                ('vacation_end_month', models.PositiveIntegerField(default=9, verbose_name='شهر نهاية الإجازة')),
                ('whatsapp_number', models.CharField(default='01555266046', max_length=30, verbose_name='رقم واتساب الدعم')),
                ('vodafone_cash_number', models.CharField(default='01551174945', max_length=30, verbose_name='رقم فودافون كاش')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات المنصة',
                'verbose_name_plural': 'إعدادات المنصة',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم المهارة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المهارة')),
                ('course_price', models.PositiveIntegerField(default=0, verbose_name='سعر الكورس كامل')),
                ('is_active', models.BooleanField(default=True, verbose_name='المهارة متاحة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدرس')),
                ('description', models.TextField(blank=True, verbose_name='وصف الدرس')),
                ('video', models.FileField(blank=True, null=True, upload_to='skill_lessons/', verbose_name='فيديو الدرس')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتيب الدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='الدرس متاح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ البداية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='subscriptionrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='main_exam_grade_4998c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='examresult',
            name='main_examre_student_606ece_idx',
        ),
        migrations.RemoveIndex(
            model_name='homework',
            name='main_homewo_grade_d1bf56_idx',
        ),
        migrations.RemoveIndex(
            model_name='homeworkanswer',
            name='main_homewo_submiss_446a6e_idx',
        ),
        migrations.RemoveIndex(
            model_name='homeworkquestion',
            name='main_homewo_homewor_3572c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='homeworkresult',
            name='main_homewo_student_a33c75_idx',
        ),
        migrations.RemoveIndex(
            model_name='homeworksubmission',
            name='main_homewo_student_49b4e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonwatchstat',
            name='main_lesson_student_af6d17_idx',
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='selected_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='curriculum_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='سعر المنهج'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='request_type',
            field=models.CharField(choices=[('initial', 'اشتراك أول مرة'), ('addition', 'إضافة مواد أو مهارات')], default='initial', max_length=20, verbose_name='نوع الطلب'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='selected_skills',
            field=models.JSONField(blank=True, default=list, verbose_name='المهارات المختارة'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='skills_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='سعر المهارات'),
        ),
        migrations.AlterField(
            model_name='subjectsubscription',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاريخ النهاية'),
        ),
        migrations.AlterField(
            model_name='subjectsubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='subjectsubscription',
            name='max_lessons',
            field=models.PositiveIntegerField(default=4, verbose_name='الحد الأقصى للحصص'),
        ),
        migrations.AlterField(
            model_name='subjectsubscription',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'شهري'), ('full_term', 'الترم كامل')], default='monthly', max_length=20, verbose_name='نوع الخطة'),
        ),
        migrations.AlterField(
            model_name='subjectsubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='subjectsubscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_subscriptions', to='main.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='subjectsubscription',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='المادة'),
        ),
        migrations.AlterField(
            model_name='subjectsubscription',
            name='watched_lessons',
            field=models.PositiveIntegerField(default=0, verbose_name='الحصص المشاهدة'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='selected_subjects',
            field=models.JSONField(blank=True, default=list, verbose_name='المواد المختارة'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='main.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='subscription_type',
            field=models.CharField(choices=[('subjects', 'مواد معينة'), ('full_term', 'الترم كامل'), ('skills', 'مهارات'), ('mixed', 'منهج + مهارات')], default='subjects', max_length=20, verbose_name='نوع الاشتراك'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='transfer_image',
            field=models.ImageField(upload_to='payments/', verbose_name='صورة التحويل'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='main.student', verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.aiconversation', verbose_name='المحادثة'),
        ),
        migrations.AddField(
            model_name='availablesubject',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_subjects', to='main.gradesetting', verbose_name='الصف'),
        ),
        migrations.AddField(
            model_name='skill',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='main.skill', verbose_name='المتطلبات السابقة'),
        ),
        migrations.AddField(
            model_name='skilllesson',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.skill', verbose_name='المهارة'),
        ),
        migrations.AddField(
            model_name='skillsubscription',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main.skill', verbose_name='المهارة'),
        ),
        migrations.AddField(
            model_name='skillsubscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_subscriptions', to='main.student', verbose_name='الطالب'),
        ),
        migrations.AddConstraint(
            model_name='availablesubject',
            constraint=models.UniqueConstraint(fields=('grade', 'school_type', 'subject_name'), name='unique_available_subject'),
        ),
        migrations.AddConstraint(
            model_name='skillsubscription',
            constraint=models.UniqueConstraint(fields=('student', 'skill'), name='unique_student_skill_subscription'),
        ),
    ]
