# Generated by Django 6.1.1 on 2026-09-13 20:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aiconversation_aimessage_availablesubject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'محادثة AI', 'verbose_name_plural': 'محادثات AI'},
        ),
        migrations.AlterModelOptions(
            name='aimessage',
            options={'ordering': ['created_at'], 'verbose_name': 'رسالة AI', 'verbose_name_plural': 'رسائل AI'},
        ),
        migrations.AlterModelOptions(
            name='availablesubject',
            options={'ordering': ['subject_name'], 'verbose_name': 'مادة متاحة', 'verbose_name_plural': 'المواد المتاحة'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at'], 'verbose_name': 'امتحان', 'verbose_name_plural': 'الامتحانات'},
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'نتيجة امتحان', 'verbose_name_plural': 'نتائج الامتحانات'},
        ),
        migrations.AlterModelOptions(
            name='gradesetting',
            options={'ordering': ['grade'], 'verbose_name': 'إعداد الصف', 'verbose_name_plural': 'إعدادات الصفوف'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-created_at'], 'verbose_name': 'واجب', 'verbose_name_plural': 'الواجبات'},
        ),
        migrations.AlterModelOptions(
            name='homeworkanswer',
            options={'verbose_name': 'إجابة واجب', 'verbose_name_plural': 'إجابات الواجبات'},
        ),
        migrations.AlterModelOptions(
            name='homeworkquestion',
            options={'ordering': ['order', 'id'], 'verbose_name': 'سؤال واجب', 'verbose_name_plural': 'أسئلة الواجبات'},
        ),
        migrations.AlterModelOptions(
            name='homeworkresult',
            options={'verbose_name': 'نتيجة واجب', 'verbose_name_plural': 'نتائج الواجبات'},
        ),
        migrations.AlterModelOptions(
            name='homeworksubmission',
            options={'verbose_name': 'تسليم واجب', 'verbose_name_plural': 'تسليمات الواجبات'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['created_at'], 'verbose_name': 'حصة', 'verbose_name_plural': 'الحصص'},
        ),
        migrations.AlterModelOptions(
            name='lessonwatchstat',
            options={'verbose_name': 'إحصائيات مشاهدة', 'verbose_name_plural': 'إحصائيات المشاهدة'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'مهارة', 'verbose_name_plural': 'المهارات'},
        ),
        migrations.AlterModelOptions(
            name='skilllesson',
            options={'ordering': ['order', 'id'], 'verbose_name': 'درس مهارة', 'verbose_name_plural': 'دروس المهارات'},
        ),
        migrations.AlterModelOptions(
            name='skillsubscription',
            options={'verbose_name': 'اشتراك مهارة', 'verbose_name_plural': 'اشتراكات المهارات'},
        ),
        migrations.AlterModelOptions(
            name='subjectsubscription',
            options={'verbose_name': 'اشتراك مادة', 'verbose_name_plural': 'اشتراكات المواد'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب اشتراك', 'verbose_name_plural': 'طلبات الاشتراك'},
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='context_type',
            field=models.CharField(choices=[('subject', 'منهج / مادة'), ('skill', 'مهارة')], default='subject', max_length=20, verbose_name='نوع المحادثة'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='main.skill', verbose_name='المهارة'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='المادة'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='curriculum_enabled',
            field=models.BooleanField(default=True, verbose_name='المنهج مفعل'),
        ),
        migrations.AddField(
            model_name='student',
            name='suspension_reason',
            field=models.TextField(blank=True, verbose_name='سبب إيقاف الحساب'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرسالة'),
        ),
        migrations.AlterField(
            model_name='availablesubject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الفصل'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النتيجة'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='gradesetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='gradesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='homeworkquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='homeworkresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النتيجة'),
        ),
        migrations.AlterField(
            model_name='homeworkresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التصحيح'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت التسليم'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الحصة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.CharField(choices=[('الصف الأول الابتدائي', 'الصف الأول الابتدائي'), ('الصف الثاني الابتدائي', 'الصف الثاني الابتدائي'), ('الصف الثالث الابتدائي', 'الصف الثالث الابتدائي'), ('الصف الرابع الابتدائي', 'الصف الرابع الابتدائي'), ('الصف الخامس الابتدائي', 'الصف الخامس الابتدائي'), ('الصف السادس الابتدائي', 'الصف السادس الابتدائي'), ('الصف الأول الإعدادي', 'الصف الأول الإعدادي'), ('الصف الثاني الإعدادي', 'الصف الثاني الإعدادي'), ('الصف الثالث الإعدادي', 'الصف الثالث الإعدادي')], max_length=100, verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='الحصة متاحة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='school_type',
            field=models.CharField(choices=[('عربي', 'عربي'), ('لغات', 'لغات')], max_length=50, verbose_name='نوع التعليم'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[('عربي', 'عربي'), ('رياضيات', 'رياضيات'), ('علوم', 'علوم'), ('دراسات', 'دراسات'), ('إنجليزي', 'إنجليزي'), ('Math', 'Math'), ('English', 'English'), ('Science', 'Science'), ('English Plus', 'English Plus')], max_length=100, verbose_name='المادة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الحصة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lessons_videos/', verbose_name='فيديو الحصة'),
        ),
        migrations.AlterField(
            model_name='lessonwatchstat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='lessonwatchstat',
            name='last_position',
            field=models.FloatField(default=0.0, verbose_name='آخر مكان'),
        ),
        migrations.AlterField(
            model_name='lessonwatchstat',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_stats', to='main.lesson', verbose_name='الحصة'),
        ),
        migrations.AlterField(
            model_name='lessonwatchstat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_stats', to='main.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='lessonwatchstat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='lessonwatchstat',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AlterField(
            model_name='lessonwatchstat',
            name='watch_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='وقت المشاهدة بالثواني'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='name',
            field=models.CharField(default='إعدادات المنصة', max_length=100, unique=True, verbose_name='اسم الإعدادات'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='skilllesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='skilllesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='skillsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='skillsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='الحساب مفعل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(default='', max_length=20, verbose_name='رقم ولي الأمر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_type',
            field=models.CharField(default='غير محدد', max_length=50, verbose_name='نوع التعليم'),
        ),
        migrations.AlterField(
            model_name='student',
            name='selected_skills',
            field=models.JSONField(blank=True, default=list, verbose_name='المهارات المختارة عند التسجيل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='طالب', max_length=100, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(default='', max_length=20, verbose_name='رقم الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='study_materials/', verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='grade',
            field=models.CharField(max_length=100, verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='material_type',
            field=models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو'), ('exam', 'امتحان')], max_length=20, verbose_name='نوع المحتوى'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='subjectsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='subjectsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة'),
        ),
    ]
