# Generated by Django 6.1.1 on 2026-09-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_aiconversation_options_alter_aimessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_chat/', verbose_name='الصورة المرسلة'),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='message',
            field=models.TextField(blank=True, verbose_name='الرسالة'),
        ),
    ]
