# Generated by Django 6.1.1 on 2026-09-19 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_aimessage_image_alter_aimessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradesetting',
            name='full_term_price',
        ),
        migrations.RemoveField(
            model_name='gradesetting',
            name='monthly_subject_price',
        ),
        migrations.AddField(
            model_name='availablesubject',
            name='full_term_price',
            field=models.PositiveIntegerField(default=0, verbose_name='سعر الترم الكامل'),
        ),
        migrations.AddField(
            model_name='availablesubject',
            name='monthly_price',
            field=models.PositiveIntegerField(default=0, verbose_name='السعر الشهري'),
        ),
        migrations.AddField(
            model_name='availablesubject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='homeworkquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.CreateModel(
            name='SkillHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الواجب')),
                ('homework_type', models.CharField(choices=[('electronic', 'واجب إلكتروني'), ('paper', 'واجب ورقي')], default='electronic', max_length=20, verbose_name='نوع الواجب')),
                ('description', models.TextField(blank=True, verbose_name='وصف الواجب')),
                ('file', models.FileField(blank=True, null=True, upload_to='skill_homework/', verbose_name='ملف الواجب')),
                ('total_marks', models.PositiveIntegerField(default=0, verbose_name='إجمالي الدرجات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('is_active', models.BooleanField(default=True, verbose_name='الواجب متاح')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='main.skill', verbose_name='المهارة')),
            ],
            options={
                'verbose_name': 'واجب مهارة',
                'verbose_name_plural': 'واجبات المهارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillHomeworkQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='السؤال')),
                ('choice_a', models.CharField(max_length=500, verbose_name='الاختيار الأول')),
                ('choice_b', models.CharField(max_length=500, verbose_name='الاختيار الثاني')),
                ('choice_c', models.CharField(blank=True, max_length=500, verbose_name='الاختيار الثالث')),
                ('choice_d', models.CharField(blank=True, max_length=500, verbose_name='الاختيار الرابع')),
                ('correct_answer', models.CharField(choices=[('a', 'الاختيار الأول'), ('b', 'الاختيار الثاني'), ('c', 'الاختيار الثالث'), ('d', 'الاختيار الرابع')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('mark', models.PositiveIntegerField(default=1, verbose_name='درجة السؤال')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتيب السؤال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.skillhomework', verbose_name='الواجب')),
            ],
            options={
                'verbose_name': 'سؤال واجب مهارة',
                'verbose_name_plural': 'أسئلة واجبات المهارات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillHomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='skill_homework_submissions/', verbose_name='ملف إجابة الطالب')),
                ('status', models.CharField(choices=[('submitted', 'تم التسليم'), ('graded', 'تم التصحيح')], default='submitted', max_length=20, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التسليم')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التصحيح')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.skillhomework', verbose_name='الواجب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_homework_submissions', to='main.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسليم واجب مهارة',
                'verbose_name_plural': 'تسليمات واجبات المهارات',
            },
        ),
        migrations.CreateModel(
            name='SkillHomeworkAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=1, verbose_name='إجابة الطالب')),
                ('is_correct', models.BooleanField(default=False, verbose_name='الإجابة صحيحة')),
                ('mark_obtained', models.PositiveIntegerField(default=0, verbose_name='الدرجة المحصلة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='main.skillhomeworkquestion', verbose_name='السؤال')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.skillhomeworksubmission', verbose_name='التسليم')),
            ],
            options={
                'verbose_name': 'إجابة واجب مهارة',
                'verbose_name_plural': 'إجابات واجبات المهارات',
            },
        ),
        migrations.CreateModel(
            name='SkillHomeworkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='الدرجة')),
                ('max_score', models.FloatField(default=0, verbose_name='الدرجة النهائية')),
                ('feedback', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النتيجة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.skillhomework', verbose_name='الواجب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_homework_results', to='main.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'نتيجة واجب مهارة',
                'verbose_name_plural': 'نتائج واجبات المهارات',
                'constraints': [models.UniqueConstraint(fields=('student', 'homework'), name='unique_student_skill_homework_result')],
            },
        ),
        migrations.AddConstraint(
            model_name='skillhomeworksubmission',
            constraint=models.UniqueConstraint(fields=('student', 'homework'), name='unique_student_skill_homework_submission'),
        ),
        migrations.AddConstraint(
            model_name='skillhomeworkanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_skill_submission_question_answer'),
        ),
    ]
