# Generated by Django 6.1.1 on 2026-09-19 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_gradesetting_full_term_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('student_phone__gt', '')), fields=('student_phone',), name='unique_nonempty_student_phone'),
        ),
    ]
