# Generated by Django 6.1.1 on 2026-09-20 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_student_unique_nonempty_student_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='main.lesson', verbose_name='الحصة المرتبطة'),
        ),
        migrations.AddField(
            model_name='lessonwatchstat',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='تمت مشاهدة الحصة'),
        ),
        migrations.AddField(
            model_name='skillhomework',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='main.skilllesson', verbose_name='الحصة المرتبطة'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='homework_submissions/', verbose_name='إجابة الطالب - صورة أو فيديو'),
        ),
        migrations.AlterField(
            model_name='skillhomeworksubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'تم التسليم'), ('pending', 'قيد التصحيح'), ('graded', 'تم التصحيح')], default='submitted', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='skillhomeworksubmission',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='skill_homework_submissions/', verbose_name='ملف إجابة الطالب - صورة أو فيديو'),
        ),
        migrations.AlterField(
            model_name='skilllesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(default='ولي الأمر', max_length=100, verbose_name='اسم ولي الأمر')),
                ('parent_phone', models.CharField(max_length=20, unique=True, verbose_name='رقم ولي الأمر')),
                ('is_active', models.BooleanField(default=True, verbose_name='حساب ولي الأمر مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'ولي أمر',
                'verbose_name_plural': 'أولياء الأمور',
                'ordering': ['parent_name'],
            },
        ),
        migrations.CreateModel(
            name='SkillLessonWatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('watch_seconds', models.PositiveIntegerField(default=0, verbose_name='وقت المشاهدة بالثواني')),
                ('last_position', models.FloatField(default=0.0, verbose_name='آخر مكان')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تمت مشاهدة الحصة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_stats', to='main.skilllesson', verbose_name='الحصة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_watch_stats', to='main.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'مشاهدة حصة مهارة',
                'verbose_name_plural': 'مشاهدات حصص المهارات',
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='unique_student_skill_lesson_watch')],
            },
        ),
    ]
