# Generated by Django 6.1.1 on 2026-09-21 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_homework_lesson_lessonwatchstat_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='context_type',
            field=models.CharField(choices=[('platform', 'مساعد المنصة'), ('subject', 'منهج / مادة'), ('skill', 'مهارة')], default='subject', max_length=20, verbose_name='نوع المحادثة'),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='كود التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء الكود')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ انتهاء الكود')),
                ('is_used', models.BooleanField(default=False, verbose_name='تم استخدام الكود')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to='main.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'كود استعادة كلمة المرور',
                'verbose_name_plural': 'أكواد استعادة كلمة المرور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='رسالة الطالب')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher_questions/images/', verbose_name='صورة الطالب')),
                ('audio', models.FileField(blank=True, null=True, upload_to='teacher_questions/audio/', verbose_name='تسجيل الطالب')),
                ('status', models.CharField(choices=[('pending', 'في انتظار الرد'), ('answered', 'تم الرد')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ السؤال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_questions', to='main.lesson', verbose_name='الدرس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_questions', to='main.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سؤال مدرس',
                'verbose_name_plural': 'أسئلة المدرس',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='رد المدرس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher_questions/replies/images/', verbose_name='صورة المدرس')),
                ('audio', models.FileField(blank=True, null=True, upload_to='teacher_questions/replies/audio/', verbose_name='تسجيل المدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرد')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.teacherquestion', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'رد مدرس',
                'verbose_name_plural': 'ردود المدرسين',
                'ordering': ['created_at'],
            },
        ),
    ]
